Using Header authentication
davidpett/ember-data-contentful pull request #19
Opened 2017-02-27 18:13 UTC by morganick

- Removing `Object.assign` since it is unsupported in Internet Explorer

2017-02-28 13:27 UTC, acorncom commented
@morganick tests failed here too

2017-02-28 15:55 UTC, morganick commented
@acorncom yeah `npm install` failed here. Is there a way to re-run the tests?

2017-03-01 18:48 UTC, davidpett requested changes
can you please update to use ES6 template literals instead of old string concat?

2017-03-01 19:03 UTC, davidpett commented
@morganick if you have time to make that change, let me know and I will cut a release, or i can merge as is and make the change.

2017-03-02 22:41 UTC, merged

2017-03-02 22:50 UTC, davidpett commented
released 0.2.1

2017-03-02 22:50 UTC, davidpett commented
thanks @morganick